# Generated by Django 2.2.4 on 2020-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='view',
            new_name='views',
        ),
    ]
